apiVersion: v1
kind: Pod
metadata:
  name: production-tapp-dummy
  namespace: default
  labels:
    app: production-tapp
spec:
  containers:
  - name: dummy
    image: nginx:alpine
    ports:
    - containerPort: 8080
    # Simple web server that responds on port 8080
    command: ["/bin/sh"]
    args:
    - -c
    - |
      mkdir -p /usr/share/nginx/html
      cat > /usr/share/nginx/html/index.html << 'EOF'
      <!DOCTYPE html>
      <html>
      <head><title>Dummy TApp</title></head>
      <body>
        <h1>Dummy Target Application</h1>
        <p>This is a placeholder pod for testing KCO operator.</p>
        <p>The real GraphQL endpoint is port-forwarded to the host.</p>
      </body>
      </html>
      EOF
      # Configure nginx to listen on port 8080
      cat > /etc/nginx/conf.d/default.conf << 'EOF'
      server {
          listen 8080;
          server_name localhost;
          location / {
              root /usr/share/nginx/html;
              index index.html;
          }
          location /graphql {
              # Proxy to the host machine where the real endpoint is port-forwarded
              proxy_pass http://10.89.0.1:3085/graphql;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
      EOF
      # Start nginx
      nginx -g 'daemon off;'
  restartPolicy: Always