kind: ConfigMap
apiVersion: v1
metadata:
  name: "{name}"
  namespace: default
data:
  config: |
    target:
      selector:
        labelSelector:
          matchLabels:
            {% for item in labels %}
            - key: {item[key]}
              value: {item[value]}
            {% endfor %}

        