apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kco-operator.fullname" . }}
  labels:
    {{- include "kco-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kco-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kco-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kco-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.config.metricsPort }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.config.healthPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: KCO_LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
            - name: KCO_LOG_FORMAT
              value: {{ .Values.config.logFormat | quote }}
            - name: KCO_GRAPHQL_TIMEOUT
              value: {{ .Values.config.graphqlTimeout | quote }}
            - name: KCO_GRAPHQL_MAX_RETRIES
              value: {{ .Values.config.graphqlMaxRetries | quote }}
            - name: KCO_DEFAULT_POLLING_INTERVAL
              value: {{ .Values.config.defaultPollingInterval | quote }}
            - name: KCO_ACTION_EXECUTION_TIMEOUT
              value: {{ .Values.config.actionExecutionTimeout | quote }}
            - name: KCO_METRICS_ENABLED
              value: {{ .Values.config.metricsEnabled | quote }}
            - name: KCO_METRICS_PORT
              value: {{ .Values.config.metricsPort | quote }}
            - name: KCO_HEALTH_PORT
              value: {{ .Values.config.healthPort | quote }}
            - name: KCO_RATE_LIMIT_REQUESTS
              value: {{ .Values.config.rateLimitRequests | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}