apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: targetworkloads.kca.dev
spec:
  scope: Namespaced
  group: kca.dev
  names:
    kind: TargetWorkload
    plural: targetworkloads
    singular: targetworkload
    shortNames:
    - targetw
    - tw
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          target:
            type: object
            properties:
              labels:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    value:
                      type: string
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
